FROM registry.cn-shenzhen.aliyuncs.com/cse-lab/cse-lab2-base

# # Set the working directory
WORKDIR /home/stu
RUN mkdir -p /tmp/mnt
# Run the binary
CMD ["./fs_client", "/tmp/mnt"]
# CMD [ "sleep","100000" ]
